# Generated by Django 6.0.2 on 2026-02-17 17:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number_type', models.CharField(blank=True, default='Service Number BA/BSS', max_length=50, null=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('rank', models.CharField(blank=True, choices=[('second_lieutenant', '2nd Lieutenant'), ('lieutenant', 'Lieutenant'), ('captain', 'Captain'), ('major', 'Major'), ('lieutenant_colonel', 'Lieutenant Colonel'), ('colonel', 'Colonel'), ('brigadier_general', 'Brigadier General'), ('major_general', 'Major General'), ('lieutenant_general', 'Lieutenant General'), ('general', 'General')], max_length=50, null=True)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('decoration', models.CharField(blank=True, max_length=100, null=True)),
                ('course_type', models.CharField(blank=True, max_length=50, null=True)),
                ('course_number', models.CharField(blank=True, max_length=50, null=True)),
                ('retirement_date', models.DateField(blank=True, null=True)),
                ('ts_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address_type', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nok_name', models.CharField(blank=True, max_length=150, null=True)),
                ('nok_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('nok_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
