# Generated by Django 6.0.2 on 2026-02-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_country_user_district_user_division_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_address',
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='present_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
