# Generated by Django 6.0.2 on 2026-02-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_full_address_user_permanent_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
        migrations.RemoveField(
            model_name='user',
            name='division',
        ),
        migrations.RemoveField(
            model_name='user',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='upazila_thana',
        ),
        migrations.AlterField(
            model_name='user',
            name='permanent_address',
            field=models.JSONField(blank=True, default=dict, help_text='Store permanent address as JSON with keys: country, division, district, upazila_thana, street_address', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='present_address',
            field=models.JSONField(blank=True, default=dict, help_text='Store present address as JSON with keys: country, division, district, upazila_thana, street_address', null=True),
        ),
    ]
