# Generated by Django 6.0.2 on 2026-02-19 06:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='tagged_friend',
        ),
        migrations.AddField(
            model_name='memory',
            name='tagged_friends',
            field=models.ManyToManyField(blank=True, related_name='tagged_memories', to=settings.AUTH_USER_MODEL),
        ),
    ]
