# Generated by Django 6.0.2 on 2026-02-21 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_messagereply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagereply',
            name='subject',
        ),
    ]
