openapi: 3.0.3

info:
  title: Notice API
  description: |
    REST API for notice board management.  
    - **Authenticated users** can read (list / retrieve) notices.  
    - **Admin / staff users** can create, update, and delete notices.  
    
    The list endpoint automatically filters out inactive notices and notices
    whose `expires_at` has passed. Results are ordered: pinned first, then
    featured, then newest.
  version: 1.0.0

servers:
  - url: http://127.0.0.1:8000
    description: Local development server
  - url: https://your-domain.com
    description: Production server

tags:
  - name: Notices
    description: Notice board operations

# ─────────────────────────────────────────────
# SECURITY SCHEMES
# ─────────────────────────────────────────────
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT access token obtained from /users/login/.

  # ─────────────────────────────────────────────
  # REUSABLE SCHEMAS
  # ─────────────────────────────────────────────
  schemas:

    # ── Notice (read) ──────────────────────────
    Notice:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          example: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
        title:
          type: string
          example: "Annual General Meeting"
        message:
          type: string
          example: "The AGM will be held on 1st March 2026 at 10:00 AM."
        is_featured:
          type: boolean
          description: Marks the notice as important / highlighted.
          example: true
        is_active:
          type: boolean
          description: Soft-hide flag. Inactive notices are not returned to users.
          example: true
        is_pinned:
          type: boolean
          description: Pinned notices appear at the top of the list.
          example: false
        expires_at:
          type: string
          format: date-time
          nullable: true
          description: |
            Optional expiry datetime (ISO 8601 / UTC).  
            If set, the notice is hidden from the list once this time has passed.
          example: "2026-03-01T18:00:00Z"
        created_at:
          type: string
          format: date-time
          readOnly: true
          example: "2026-02-01T09:30:00Z"

    # ── Notice write (create / update) ─────────
    NoticeRequest:
      type: object
      required:
        - title
        - message
      properties:
        title:
          type: string
          maxLength: 255
          example: "Annual General Meeting"
        message:
          type: string
          example: "The AGM will be held on 1st March 2026 at 10:00 AM."
        is_featured:
          type: boolean
          default: false
          example: true
        is_active:
          type: boolean
          default: true
          example: true
        is_pinned:
          type: boolean
          default: false
          example: false
        expires_at:
          type: string
          format: date-time
          nullable: true
          example: "2026-03-01T18:00:00Z"

    # ── Errors ─────────────────────────────────
    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
          example: "Authentication credentials were not provided."

    ValidationErrorResponse:
      type: object
      description: Field-level validation errors.
      additionalProperties:
        type: array
        items:
          type: string
      example:
        title:
          - "This field is required."
        message:
          - "This field may not be blank."


# ─────────────────────────────────────────────
# PATHS
# ─────────────────────────────────────────────
paths:

  # ── List / Create ──────────────────────────
  /notice/notices/:
    get:
      tags:
        - Notices
      summary: List all active notices
      description: |
        Returns all notices that are:
        - `is_active = true`
        - `expires_at` is null **or** has not yet passed

        Results are ordered: **pinned → featured → newest**.

        > **Permission:** Any authenticated user.
      operationId: noticeList
      security:
        - BearerAuth: []
      responses:
        '200':
          description: A list of active notices.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notice'
              example:
                - id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                  title: "Annual General Meeting"
                  message: "The AGM will be held on 1st March 2026 at 10:00 AM."
                  is_featured: true
                  is_active: true
                  is_pinned: true
                  expires_at: "2026-03-01T18:00:00Z"
                  created_at: "2026-02-01T09:30:00Z"
        '401':
          description: Authentication credentials were not provided or are invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      tags:
        - Notices
      summary: Create a new notice
      description: |
        Creates a new notice. The `created_by` field is automatically set to the
        currently authenticated admin user — it is not accepted in the request body.

        > **Permission:** Admin / staff only.
      operationId: noticeCreate
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoticeRequest'
      responses:
        '201':
          description: Notice created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notice'
        '400':
          description: Validation error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden — caller is not an admin/staff user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  # ── Retrieve / Update / Delete ─────────────
  /notice/notices/{id}/:
    parameters:
      - name: id
        in: path
        required: true
        description: UUID of the notice.
        schema:
          type: string
          format: uuid

    get:
      tags:
        - Notices
      summary: Retrieve a notice
      description: |
        Returns a single notice by UUID.  
        Only active, non-expired notices are accessible to regular users.

        > **Permission:** Any authenticated user.
      operationId: noticeRetrieve
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Notice retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notice'
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Notice not found (does not exist, is inactive, or has expired).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      tags:
        - Notices
      summary: Fully update a notice
      description: |
        Replaces all writable fields of the notice. All required fields must be provided.

        > **Permission:** Admin / staff only.
      operationId: noticeUpdate
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoticeRequest'
      responses:
        '200':
          description: Notice updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notice'
        '400':
          description: Validation error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden — caller is not an admin/staff user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Notice not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    patch:
      tags:
        - Notices
      summary: Partially update a notice
      description: |
        Updates one or more fields of the notice. Only provided fields are changed.

        > **Permission:** Admin / staff only.
      operationId: noticePartialUpdate
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoticeRequest'
      responses:
        '200':
          description: Notice partially updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notice'
        '400':
          description: Validation error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden — caller is not an admin/staff user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Notice not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      tags:
        - Notices
      summary: Delete a notice
      description: |
        Permanently deletes the notice. Consider using `PATCH` to set
        `is_active: false` for a soft-hide instead.

        > **Permission:** Admin / staff only.
      operationId: noticeDestroy
      security:
        - BearerAuth: []
      responses:
        '204':
          description: Notice deleted successfully. No content returned.
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden — caller is not an admin/staff user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Notice not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'