openapi: 3.0.3
info:
  title: Gallery Memory API
  description: API for managing memories and memory photos
  version: 1.4.0

servers:
  - url: /memory
    description: Gallery base path

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    TaggedFriendDetail:
      type: object
      description: Read-only detailed info of a tagged friend (returned in responses via tagged_friends_details)
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          example: "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
        full_name:
          type: string
          example: "John Doe"
        number:
          type: string
          example: "+8801712345678"
        number_type:
          type: string
          example: "mobile"
        rank:
          type: string
          example: "Captain"

    MemoryPhoto:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          example: "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
        image:
          type: string
          format: uri
          example: "https://example.com/media/memories/user_1/photo.jpg"
        captured_at:
          type: string
          format: date-time
          nullable: true
          example: "2024-06-15T10:30:00Z"

    Memory:
      type: object
      description: >
        Full memory object returned in responses.
        `tagged_friends` is write-only (used for input as a list of user UUIDs/PKs).
        `tagged_friends_details` is read-only (returned in output with full user info).
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          example: "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
        title:
          type: string
          maxLength: 255
          example: "Summer Vacation 2024"
        description:
          type: string
          example: "A wonderful trip to the mountains"
        tagged_friends_details:
          type: array
          readOnly: true
          description: >
            Detailed info of each tagged friend. Read-only — use `tagged_friends`
            (list of user PKs) to write.
          items:
            $ref: '#/components/schemas/TaggedFriendDetail'
        created_at:
          type: string
          format: date-time
          readOnly: true
          example: "2024-06-15T10:00:00Z"
        photos:
          type: array
          readOnly: true
          items:
            $ref: '#/components/schemas/MemoryPhoto'

    MemoryCreate:
      type: object
      required:
        - title
      description: >
        Payload for creating or updating a memory.
        Use `tagged_friends` (list of user PKs) to tag friends.
        The response will return friend details under `tagged_friends_details`.
        `tagged_friends` is write-only and will not appear in responses.
      properties:
        title:
          type: string
          maxLength: 255
          example: "Summer Vacation 2024"
        description:
          type: string
          example: "A wonderful trip to the mountains"
        tagged_friends:
          type: array
          writeOnly: true
          description: >
            Write-only. List of user PKs to tag. Omit to keep existing tags (PATCH).
            Pass `[]` to remove all tags.
          items:
            type: integer
          example: [1, 2, 3]

    PhotoUploadSuccess:
      type: object
      properties:
        message:
          type: string
          example: "Photo uploaded successfully"
        photo_id:
          type: string
          format: uuid
          example: "3f2504e0-4f89-11d3-9a0c-0305e82c3301"

    ValidationError:
      type: object
      additionalProperties:
        type: array
        items:
          type: string
      example:
        title: ["This field is required."]
        image: ["No file was submitted."]

    NotFound:
      type: object
      properties:
        detail:
          type: string
          example: "Not found."

    Forbidden:
      type: object
      properties:
        detail:
          type: string
          example: "You cannot upload photos to this memory."

    Unauthorized:
      type: object
      properties:
        detail:
          type: string
          example: "Authentication credentials were not provided."

paths:

  /memory/memories/:
    get:
      tags:
        - Memories
      summary: List memories
      description: >
        **Normal users** — returns only their own uploaded memories
        (filtered by `uploader=request.user`).

        **Admin / Superuser** (`is_staff` or `is_superuser`) — returns all memories
        across all users.

        Each memory includes `tagged_friends_details` with full user info of tagged friends.
      responses:
        '200':
          description: List of memories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Memory'
              example:
                - id: "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                  title: "Birthday Party"
                  description: "John's surprise party"
                  tagged_friends_details:
                    - id: "4f2504e0-4f89-11d3-9a0c-0305e82c3302"
                      full_name: "Jane Smith"
                      number: "+8801712345678"
                      number_type: "mobile"
                      rank: "Lieutenant"
                    - id: "5f2504e0-4f89-11d3-9a0c-0305e82c3303"
                      full_name: "Bob Lee"
                      number: "+8801812345678"
                      number_type: "mobile"
                      rank: "Sergeant"
                  created_at: "2024-06-15T10:00:00Z"
                  photos:
                    - id: "6f2504e0-4f89-11d3-9a0c-0305e82c3304"
                      image: "https://example.com/media/memories/photo1.jpg"
                      captured_at: "2024-06-15T10:30:00Z"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'

    post:
      tags:
        - Memories
      summary: Create a new memory
      description: >
        Creates a memory. The `uploader` is automatically set to `request.user`.

        Use `tagged_friends` (list of integer PKs) to tag friends.
        Response will include `tagged_friends_details` with full user objects.

        `tagged_friends` is write-only and will not appear in responses.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemoryCreate'
            examples:
              single_tag:
                summary: Tag a single friend
                value:
                  title: "Birthday Party"
                  description: "John's surprise birthday party"
                  tagged_friends: [3]
              multiple_tags:
                summary: Tag multiple friends
                value:
                  title: "Road Trip"
                  description: "Weekend road trip with the crew"
                  tagged_friends: [1, 2, 3]
              no_tags:
                summary: No tagged friends
                value:
                  title: "Solo Hike"
                  description: "Early morning hike at the national park"
      responses:
        '201':
          description: Memory created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Memory'
              example:
                id: "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                title: "Road Trip"
                description: "Weekend road trip with the crew"
                tagged_friends_details:
                  - id: "4f2504e0-4f89-11d3-9a0c-0305e82c3302"
                    full_name: "Alice"
                    number: "+8801711111111"
                    number_type: "mobile"
                    rank: "Major"
                  - id: "5f2504e0-4f89-11d3-9a0c-0305e82c3303"
                    full_name: "Bob"
                    number: "+8801722222222"
                    number_type: "mobile"
                    rank: "Captain"
                created_at: "2024-06-20T09:00:00Z"
                photos: []
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'

  /memory/memories/{id}/:
    parameters:
      - name: id
        in: path
        required: true
        description: UUID primary key of the memory
        schema:
          type: string
          format: uuid
          example: "3f2504e0-4f89-11d3-9a0c-0305e82c3301"

    get:
      tags:
        - Memories
      summary: Retrieve a memory
      description: >
        Returns a single memory with nested `photos` and `tagged_friends_details`.

        **Normal users** can only access their own memories — others return `404`
        because the queryset is filtered to `uploader=request.user`.

        **Admin / Superuser** can access any memory.
      responses:
        '200':
          description: Memory detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Memory'
              example:
                id: "3f2504e0-4f89-11d3-9a0c-0305e82c3301"
                title: "Summer Vacation 2024"
                description: "A wonderful trip to the mountains"
                tagged_friends_details:
                  - id: "4f2504e0-4f89-11d3-9a0c-0305e82c3302"
                    full_name: "Jane Smith"
                    number: "+8801712345678"
                    number_type: "mobile"
                    rank: "Lieutenant"
                created_at: "2024-06-15T10:00:00Z"
                photos:
                  - id: "5f2504e0-4f89-11d3-9a0c-0305e82c3303"
                    image: "https://example.com/media/memories/photo1.jpg"
                    captured_at: "2024-06-15T10:30:00Z"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '404':
          description: Memory not found or not owned by requesting user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'

    put:
      tags:
        - Memories
      summary: Full update a memory
      description: >
        Fully replaces all writable fields of a memory.

        **Normal users** can only update their own memories (others return `404`).

        **Admin / Superuser** can update any memory.

        Pass `tagged_friends: []` to remove all tags.
        `tagged_friends` is write-only and will not appear in responses.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemoryCreate'
            examples:
              full_update:
                summary: Full update with tags
                value:
                  title: "Updated Title"
                  description: "Updated description"
                  tagged_friends: [1, 2]
              clear_tags:
                summary: Remove all tagged friends
                value:
                  title: "Updated Title"
                  description: "Updated description"
                  tagged_friends: []
      responses:
        '200':
          description: Memory updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Memory'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'

    patch:
      tags:
        - Memories
      summary: Partial update a memory
      description: >
        Updates only the provided fields. Omitted fields remain unchanged.

        **Normal users** can only update their own memories (others return `404`).

        **Admin / Superuser** can update any memory.

        If `tagged_friends` is omitted, existing tags are preserved.
        Pass `tagged_friends: []` to remove all tags.
        `tagged_friends` is write-only and will not appear in responses.
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemoryCreate'
            examples:
              title_only:
                summary: Update title only
                value:
                  title: "New Title"
              update_tags:
                summary: Update tagged friends only
                value:
                  tagged_friends: [3, 4]
              clear_tags:
                summary: Remove all tagged friends
                value:
                  tagged_friends: []
      responses:
        '200':
          description: Memory updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Memory'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'

    delete:
      tags:
        - Memories
      summary: Delete a memory
      description: >
        Deletes a memory and all its associated `MemoryPhoto` records (CASCADE).

        **Normal users** can only delete their own memories (others return `404`).

        **Admin / Superuser** can delete any memory.
      responses:
        '204':
          description: Memory deleted successfully (no content)
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'

  /memory/memories/{memory_id}/photos/:
    parameters:
      - name: memory_id
        in: path
        required: true
        description: UUID primary key of the memory to upload a photo to
        schema:
          type: string
          format: uuid
          example: "3f2504e0-4f89-11d3-9a0c-0305e82c3301"

    post:
      tags:
        - Memory Photos
      summary: Upload a single photo to a memory
      description: >
        Uploads one photo to a specific memory using `multipart/form-data`.

        The image is saved as a `MemoryPhoto` record linked to the memory.

        **Normal users** can only upload to their own memories.
        Attempting to upload to another user's memory returns `403 Forbidden`.

        **Admin / Superuser** (`is_staff`) can upload to any memory.

        > **Note:** This endpoint accepts a single image per request.
        > Submit multiple requests to upload multiple photos.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - image
              properties:
                image:
                  type: string
                  format: binary
                  description: A single image file to upload (JPEG, PNG, or WebP)
                captured_at:
                  type: string
                  format: date-time
                  nullable: true
                  description: >
                    Date and time when the photo was captured. Optional.
                  example: "2024-06-15T10:30:00Z"
            encoding:
              image:
                contentType: image/png, image/jpeg, image/webp
      responses:
        '201':
          description: Photo uploaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PhotoUploadSuccess'
              example:
                message: "Photo uploaded successfully"
                photo_id: "6f2504e0-4f89-11d3-9a0c-0305e82c3304"
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
              example:
                image: ["No file was submitted."]
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '403':
          description: Forbidden — memory belongs to a different user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forbidden'
        '404':
          description: Memory not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'